# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\plot_dialog_gui.ui'
#
# Created: Sat Apr 09 00:51:08 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(615, 362)
        self.horizontalLayoutWidget = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 280, 601, 80))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.b_plot_real = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.b_plot_real.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/imag/real_button.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_plot_real.setIcon(icon)
        self.b_plot_real.setIconSize(QtCore.QSize(64, 64))
        self.b_plot_real.setObjectName(_fromUtf8("b_plot_real"))
        self.horizontalLayout.addWidget(self.b_plot_real)
        self.b_plot_complex = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.b_plot_complex.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/imag/complex_button.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_plot_complex.setIcon(icon1)
        self.b_plot_complex.setIconSize(QtCore.QSize(64, 64))
        self.b_plot_complex.setObjectName(_fromUtf8("b_plot_complex"))
        self.horizontalLayout.addWidget(self.b_plot_complex)
        self.b_plot_fft = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.b_plot_fft.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/imag/fft.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_plot_fft.setIcon(icon2)
        self.b_plot_fft.setIconSize(QtCore.QSize(64, 64))
        self.b_plot_fft.setObjectName(_fromUtf8("b_plot_fft"))
        self.horizontalLayout.addWidget(self.b_plot_fft)
        self.b_clean = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.b_clean.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/imag/clean.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_clean.setIcon(icon3)
        self.b_clean.setIconSize(QtCore.QSize(64, 64))
        self.b_clean.setObjectName(_fromUtf8("b_clean"))
        self.horizontalLayout.addWidget(self.b_clean)
        self.b_done = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.b_done.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/imag/done.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_done.setIcon(icon4)
        self.b_done.setIconSize(QtCore.QSize(64, 64))
        self.b_done.setObjectName(_fromUtf8("b_done"))
        self.horizontalLayout.addWidget(self.b_done)
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(510, 30, 61, 61))
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setPixmap(QtGui.QPixmap(_fromUtf8(":/imag/graph_pic.png")))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayoutWidget = QtGui.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(240, 10, 201, 91))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.e_num_fft_points = QtGui.QLineEdit(self.gridLayoutWidget)
        self.e_num_fft_points.setObjectName(_fromUtf8("e_num_fft_points"))
        self.gridLayout_2.addWidget(self.e_num_fft_points, 1, 1, 1, 1)
        self.e_sample_freq = QtGui.QLineEdit(self.gridLayoutWidget)
        self.e_sample_freq.setObjectName(_fromUtf8("e_sample_freq"))
        self.gridLayout_2.addWidget(self.e_sample_freq, 0, 1, 1, 1)
        self.layoutWidget = QtGui.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 219, 101))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.e_color = QtGui.QLineEdit(self.layoutWidget)
        self.e_color.setObjectName(_fromUtf8("e_color"))
        self.gridLayout.addWidget(self.e_color, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.e_subplot = QtGui.QLineEdit(self.layoutWidget)
        self.e_subplot.setObjectName(_fromUtf8("e_subplot"))
        self.gridLayout.addWidget(self.e_subplot, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.e_dimension = QtGui.QLineEdit(self.layoutWidget)
        self.e_dimension.setObjectName(_fromUtf8("e_dimension"))
        self.gridLayout.addWidget(self.e_dimension, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 140, 601, 31))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.b_cb_hold = QtGui.QCheckBox(self.horizontalLayoutWidget_2)
        self.b_cb_hold.setObjectName(_fromUtf8("b_cb_hold"))
        self.horizontalLayout_2.addWidget(self.b_cb_hold)
        self.p_progress_bar = QtGui.QProgressBar(self.horizontalLayoutWidget_2)
        self.p_progress_bar.setProperty("value", 0)
        self.p_progress_bar.setObjectName(_fromUtf8("p_progress_bar"))
        self.horizontalLayout_2.addWidget(self.p_progress_bar)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 180, 601, 41))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_6 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.b_column_choose = QtGui.QComboBox(self.horizontalLayoutWidget_3)
        self.b_column_choose.setObjectName(_fromUtf8("b_column_choose"))
        self.horizontalLayout_4.addWidget(self.b_column_choose)
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.b_slider = QtGui.QSlider(self.horizontalLayoutWidget_3)
        self.b_slider.setMinimum(1)
        self.b_slider.setMaximum(1000)
        self.b_slider.setSingleStep(1)
        self.b_slider.setProperty("value", 1)
        self.b_slider.setTracking(True)
        self.b_slider.setOrientation(QtCore.Qt.Horizontal)
        self.b_slider.setInvertedAppearance(False)
        self.b_slider.setInvertedControls(False)
        self.b_slider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.b_slider.setTickInterval(50)
        self.b_slider.setObjectName(_fromUtf8("b_slider"))
        self.horizontalLayout_4.addWidget(self.b_slider)
        self.l_average_window = QtGui.QLabel(Dialog)
        self.l_average_window.setGeometry(QtCore.QRect(240, 230, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.l_average_window.setFont(font)
        self.l_average_window.setObjectName(_fromUtf8("l_average_window"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Plot", None))
        self.label_9.setText(_translate("Dialog", "Nfft", None))
        self.label_8.setText(_translate("Dialog", "Fs", None))
        self.e_num_fft_points.setText(_translate("Dialog", "0", None))
        self.e_sample_freq.setText(_translate("Dialog", "245.76", None))
        self.e_color.setText(_translate("Dialog", "#0000ff", None))
        self.label_2.setText(_translate("Dialog", "Color", None))
        self.e_subplot.setText(_translate("Dialog", "111", None))
        self.label_4.setText(_translate("Dialog", "Subplot", None))
        self.e_dimension.setText(_translate("Dialog", "111", None))
        self.label.setText(_translate("Dialog", "Dimensions", None))
        self.b_cb_hold.setText(_translate("Dialog", "Hold", None))
        self.p_progress_bar.setFormat(_translate("Dialog", "%p%", None))
        self.label_6.setText(_translate("Dialog", "I/Q Data Select:", None))
        self.label_3.setText(_translate("Dialog", "Average:", None))
        self.l_average_window.setText(_translate("Dialog", "Running Average = 1", None))

import resource_rc
